POST http://localhost:4000/Pulse/Admin/Project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User

{
  "Project_Name":"p5",
  "GDO_Head":"g3@westagilelabs.com",
  "Project_Manager":"pm1@westagilelabs.com",
  "Client_id":"1",
  "Project_Status":"Completed",
  "Project_Start_Date":"10-12-2022",
  "Project_End_Date":"10-10-2023",
  "Project_Fitness_Indicator":"Green",
  "Project_Domain":"Mobile",
  "Project_Type":"Performance Testing",
  "Allocation_Type":"Temperory"
}
###
PUT http://localhost:4000/Pulse/Admin/Project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User

{
  "Project_Name":"p4",
  "GDO_Head":"g1@westagilelabs.com",
  "Project_End_Date":"12-11-2022",
  "Allocation_Type":"Permanent"
 
}
###
DELETE http://localhost:4000/Pulse/Admin/Project/p4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User
###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User
###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User


###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard/4/ProjectDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User

###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard/2/ProjectUpdates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User
###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard/1/TeamComposition
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User

###
GET http://localhost:4000/Pulse/Admin/PotfolioDashboard/2/ProjectConcerns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MjkwMzUsImV4cCI6MTY3ODkwMTgzNX0.ji5Lh0Ekc0rUgk1q3g-6Rd7Yi7nMhS6Izxd_o89-rXA .Admin User

###
