POST http://localhost:4000/pulse/gdoHead/gdo1@westagilelabs.com/teamMembers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAxNjI5NTIsImV4cCI6MTY4MDMzNTc1Mn0.sEUQWMiYS0QZ_tbgefROn6mUKzihRyZaFgqBMGwtniY .gdoHead

{
  "email":"a@westagilelabs.com",
  "projectId":"2",
  "role":"tester",
  "startDate":"2022-01-20",
  "endDate":null,
  "status":"cctive",
  "exposedToClient":false,
  "billingStatus":"billed",
  "allocation_Type":"temperory"
}

###
PUT http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/teamMembers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead

{
  "email":"a@westagilelabs.com",
  "projectId":"1",
  "allocationType":"temp"
  
}
###
DELETE http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/teamMembers/a@westagilelabs.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead

###
GET http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/portfolioDashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead
###
GET http://localhost:4000/pulse/gdoHead/gdo1@westagilelabs.com/projectId/2/detailedView
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAwODgyMjMsImV4cCI6MTY4MDI2MTAyM30.RupgC9uHSZ8XzzYa9jf7gjjUawv063jUx68E4EEXIsk .gdoHead


###
GET http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/projectId/1/projectDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead

###
GET http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/projectId/1/projectUpdates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead
###
GET http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/projectId/1/teamComposition
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead

###
GET http://localhost:4000/pulse/gdoHead/g1@westagilelabs.com/projectId/2/projectConcerns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQ3MzgsImV4cCI6MTY3OTE0NzUzOH0.O0fdJB9ZKTz30J7IBi1Eoe9pYXCaVrTKtL7hkeU_8L0 .gdoHead

###
GET http://localhost:4000/pulse/gdoHead/gdo1@westagilelabs.com/resourceRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODEyMDE5MDQsImV4cCI6MTY4MTM3NDcwNH0.2LYkdQrw12FFJNtuYzQo_d00b2BAmfWoDHgNnbx92Zk .gdoHead
###
POST http://localhost:4000/pulse/gdoHead/gdo1@westagilelabs.com/projectId/2/resourceRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODEyMDE5MDQsImV4cCI6MTY4MTM3NDcwNH0.2LYkdQrw12FFJNtuYzQo_d00b2BAmfWoDHgNnbx92Zk .gdoHead
Content-Type: application/json

{
  "projectId":2,
  "requestRaisedBy":"au1@westagilelabs.com",
  "resourceDesc":"rr1"



}

###
GET http://localhost:4000/pulse/gdoHead/gdo1@westagilelabs.com/concerns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAwODAwODMsImV4cCI6MTY4MDI1Mjg4M30.ePkY-qiBBZLC4nw2VHrsqJDnID-iLYlAj3HnWwXyNc4 .gdoHead
