POST http://localhost:4000/Pulse/ProjectManager/pm3@westagilelabs.com/Concerns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

{
  
  "Project_id":"2",
  "Concern_Desc":"Doubt",
  "Concern_Raised_By":"pm1@westagilelabs.com",
  "Concern_Raised_On":"2023-10-10",
  "Concern_Severity":"Medium",
  "Concern_Indicator":"green",
  "Concern_Raised_From_Client":0,
  "Concern_Status":"Raised",
  "Concern_Mitigated_Date":"2023-03-10"
}
###
POST http://localhost:4000/Pulse/ProjectManager/pm2@westagilelabs.com/ProjectUpdates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

{
  
  "Project_id":"2",
  "Project_Status_Update":"Sales",
  "Schedule_Status":"Amber",
  "Resourcing_Status":"Green",
  "Quality_Status":"Amber",
  "Waiting_For_Client_Inputs":0,
  "Updated_On":"2023-03-10"
  
}
###
POST http://localhost:4000/Pulse/ProjectManager/pm2@westagilelabs.com/ResourceRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

{
  
  "Request_Raised_By":"pm1@westagilelabs.com",
  "Project_id":"2",
  "Resource_Desc":"Need Team Members"
 
}

###
GET http://localhost:4000/Pulse/ProjectManager/pm4@westagilelabs.com/ProjectDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

###
GET http://localhost:4000/Pulse/ProjectManager/pm2@westagilelabs.com/ProjectUpdates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager
###
GET http://localhost:4000/Pulse/ProjectManager/pm3@westagilelabs.com/TeamComposition
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

###
GET http://localhost:4000/Pulse/ProjectManager/g1@westagilelabs.com/ProjectConcerns
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg3MzA1NDksImV4cCI6MTY3ODkwMzM0OX0.fnPA7XrIhuIWc3eYtNlhc0G6uKyUTR0sT-Cr3ICRFUA .Project Manager

###
