POST http://localhost:4000/pulse/employee/pm1@westagilelabs.com/register
Content-Type: application/json

{
  "email":"pm1@westagilelabs.com",
    "password":"pm1"

}
###
POST http://localhost:4000/pulse/employee/pm1@westagilelabs.com/login
Content-Type: application/json

{
  "email":"pm1@westagilelabs.com",
  "password":"pm1"
}

###
POST http://localhost:4000/pulse/employee/pm1@westagilelabs.com/forgotPassword
Content-Type: application/json

{
  "email":"s@westagilelabs.com"
}
###
PUT http://localhost:4000/pulse/employee/pm1@westagilelabs.com/resetPassword
Content-Type: application/json

{
  "email":"s@westagilelabs.com",
  "password":"ss",
  "otp":"741226"
}


###
POST http://localhost:4000/Pulse/employee/roleMapping
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Nzg5NzQxMjgsImV4cCI6MTY3OTE0NjkyOH0.nI7_IcXld5yexihWp7v5WPdRbZCOqFHkZSVgW3dlpQM .superAdmin

{
  "SuperAdmin":"s@westagilelabs.com", 
  "user":"pm2@westagilelabs.com",
  "userRole":"projectManager"
}
